//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VicFireReader {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class VicFireReaderSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static VicFireReaderSettings defaultInstance = ((VicFireReaderSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new VicFireReaderSettings())));
        
        public static VicFireReaderSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SimulationModeEnabled {
            get {
                return ((bool)(this["SimulationModeEnabled"]));
            }
            set {
                this["SimulationModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveCFARSSFeeds {
            get {
                return ((bool)(this["SaveCFARSSFeeds"]));
            }
            set {
                this["SaveCFARSSFeeds"] = value;
            }
        }
    }
}
